<?php

/**
 * @file esdportal_api.module
 */

use Tobscure\JsonApi\Document;
use Drupal\esdportal_api\Serializers\EcSerializer;

define("ESDPORTAL_API_DEFAULT_LIMIT", 100);
define("ESDPORTAL_API_MAX_LIMIT", 1000);

/**
 * Implements hook_services_resources().
 *
 * Defines resources for special (non-standard) ESD Portal data.
 */
function esdportal_api_services_resources() {
  $api = array(
    'ecs' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves Early Childhood Center',
          'callback' => '_esdportal_api_retrieve_ec',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'id',
              'type' => 'int',
              'description' => 'ec entity ID',
              'source' => array('path' => '0'),
              'optional' => FALSE,
              'default value' => NULL,
            ),
          ),
        ),
        'index' => array(
          'help' => 'Lists Early Childhood Centers',
          'callback' => '_esdportal_api_index_ecs',
          'access arguments' => array('access content'),
          'args' => array(
            array(
              'name' => 'includes',
              'type' => 'string',
              'description' => 'Include other datasets, comma-separated',
              'source' => array('param' => 'includes'),
              'optional' => TRUE,
              'default value' => null,
            ),
          ),
        ),
      ),
    ),
    'ec_state_ratings' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves state ratings for an Early Childhood Center',
          'callback' => '_esdportal_api_retrieve_ec_state_rating',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'esd_ec_id',
              'type' => 'int',
              'description' => 'ESD-universe early childhood center ID',
              'source' => array('path' => '0'),
              'optional' => FALSE,
              'default value' => NULL,
            ),
            array(
              'name' => 'batch_timestamp',
              'type' => 'int',
              'description' => 'UNIX timestamp of a specific batch (if not provided, returns most recent rating)',
              'source' => array('param' => 'batch_timestamp'),
              'optional' => TRUE,
              'default value' => NULL,
            ),
          ),
        ),
        'index' => array(
          'help' => 'Lists most recent Early Childhood Center state ratings',
          'callback' => '_esdportal_api_index_ec_state_ratings',
          'access arguments' => array('access content'),
          'args' => array(
            array(
              'name' => 'batch_timestamp',
              'type' => 'int',
              'description' => 'UNIX timestamp of a specific batch (if not provided, returns most recent ratings)',
              'source' => array('path' => '1'),
              'optional' => TRUE,
              'default value' => NULL,
            ),
          ),
        ),
      ),
    ),
  );

  return $api;
}

/**
 * Stub.
 */
function _esdportal_api_retrieve_ec($id) {
  $document = new Document;

  $ec = taxonomy_term_load($id);
  $ec->ec_profile_ids = taxonomy_select_nodes($ec->tid, FALSE);
  $ec->ec_profiles = array_map(function($ec_profile_id) {
    return node_load($ec_profile_id);
  }, $ec->ec_profile_ids);

  $serializer = new EcSerializer(['ec_profiles']);

  $resource = $serializer->resource($ec);

  $document->setData($resource);

  return $document->toArray();
}

/**
 * Retrieves list of all early childhood centers.
 *
 * @param $includes
 *   related datasets to include, comma-separated
 */
function _esdportal_api_index_ecs($includes = null) {
  $document = new Document;

  $ecs = taxonomy_get_tree(19, 0, null, true);

  $includes = explode(',', $includes);

  $serializer = (count($includes) > 0) ? new EcSerializer($includes) : new EcSerializer([], ['ec_profiles']);

  foreach ($ecs as &$ec) {
    $ec->ec_profile_ids = taxonomy_select_nodes($ec->tid, FALSE);
  }
  unset($ec);

  if (in_array('ec_profiles', $includes)) {
    foreach ($ecs as $ec) {
      $ec->ec_profiles = array_map(function($ec_profile_id) {
        return node_load($ec_profile_id);
      }, $ec->ec_profile_ids);
    }
  }

  $collection = $serializer->collection($ecs);

  $document->setData($collection);

  $document->addMeta('total', count($ecs));

  return $document->toArray();
}

/**
 * Retrieves a single EC Center's rating with given timestamp or most recent timestamp if none is given.
 *
 * @param $esd_ec_id
 *
 * @param $batch_timestamp
 */
function _esdportal_api_retrieve_ec_state_rating($esd_ec_id, $batch_timestamp) {
  if (isset($batch_timestamp) && $batch_timestamp > 0) {
    $rating = db_query('SELECT * FROM {ec_state_ratings} WHERE timestamp=:batch_timestamp AND esd_ec_id=:esd_ec_id', array(':esd_ec_id' => $esd_ec_id, ':batch_timestamp' => $batch_timestamp))->fetchAssoc();
  } else {
    $rating = db_query('SELECT * FROM {ec_state_ratings} WHERE timestamp=(SELECT MAX(timestamp) FROM {ec_state_ratings}) AND esd_ec_id=:esd_ec_id', array(':esd_ec_id' => $esd_ec_id))->fetchAssoc();
  }
  return $rating;
}

/**
 * Lists all batch timestamps.
 *
 * (not offered via api yet)
 */
function _esdportal_api_index_ec_state_ratings_batches() {
  return db_query('SELECT DISTINCT(timestamp) FROM {ec_state_ratings} ORDER BY timestamp DESC')->fetchAssoc();
}

/**
 * Lists set of EC state ratings with given timestamp or most recent timestamp if none is given.
 *
 * @param int $batch_timestamp
 */
function _esdportal_api_index_ec_state_ratings($batch_timestamp) {
  if (isset($batch_timestamp) && $batch_timestamp > 0) {
    $ratings = db_query('SELECT * FROM {ec_state_ratings} WHERE timestamp=:batch_timestamp', array(':batch_timestamp' => $batch_timestamp))->fetchAssoc();
  } else {
    $ratings = db_query('SELECT * FROM {ec_state_ratings} WHERE timestamp=(SELECT MAX(timestamp) FROM {ec_state_ratings})')->fetchAll();
  }

  return array('ec_state_ratings' => $ratings);
}
