<?php
/**
 * @file
 * esdportal_e3_feature.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function esdportal_e3_feature_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'e3_contact-teacher-field_contact_addy'
  $field_instances['e3_contact-teacher-field_contact_addy'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'addressfield',
        'settings' => array(
          'format_handlers' => array(
            0 => 'address',
          ),
          'use_widget_handlers' => 1,
        ),
        'type' => 'addressfield_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_contact_addy',
    'label' => 'Home address',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'addressfield',
      'settings' => array(
        'available_countries' => array(
          'US' => 'US',
        ),
        'default_country' => 'site_default',
        'format_handlers' => array(
          'address' => 'address',
          'phone' => 'phone',
          'address-optional' => 'address-optional',
          'address-hide-postal-code' => 0,
          'address-hide-street' => 0,
          'address-hide-country' => 0,
          'organisation' => 0,
          'name-full' => 0,
          'name-oneline' => 0,
          'address-us-with-county' => 0,
        ),
        'phone_number_fields' => array(
          'extension' => 0,
          'fax' => 0,
          'mobile' => 'mobile',
          'phone' => 'phone',
        ),
      ),
      'type' => 'addressfield_standard',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_e3_cohort'
  $field_instances['e3_contact-teacher-field_e3_cohort'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 8,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_e3_cohort',
    'label' => 'Cohort',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_e3_status'
  $field_instances['e3_contact-teacher-field_e3_status'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_e3_status',
    'label' => 'Status',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_ec'
  $field_instances['e3_contact-teacher-field_ec'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_ec',
    'label' => 'Employing Early Childhood Center',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_email'
  $field_instances['e3_contact-teacher-field_email'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_email',
    'label' => 'Email',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_teacher_ec_role'
  $field_instances['e3_contact-teacher-field_teacher_ec_role'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_teacher_ec_role',
    'label' => 'Position / role',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_attendance'
  $field_instances['e3_contact-teacher-field_training_attendance'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 13,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_attendance',
    'label' => 'Training Attendance',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_f1'
  $field_instances['e3_contact-teacher-field_training_hours_f1'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 14,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_f1',
    'label' => 'Fall Training Day 1 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_f2'
  $field_instances['e3_contact-teacher-field_training_hours_f2'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 15,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_f2',
    'label' => 'Fall Training Day 2 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_f3'
  $field_instances['e3_contact-teacher-field_training_hours_f3'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 16,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_f3',
    'label' => 'Fall Training Day 3 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 14,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_m1'
  $field_instances['e3_contact-teacher-field_training_hours_m1'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 17,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_m1',
    'label' => 'Mid-Fall Training Day 1 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_m2'
  $field_instances['e3_contact-teacher-field_training_hours_m2'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 18,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_m2',
    'label' => 'Mid-Fall Training Day 2 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 16,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_s1'
  $field_instances['e3_contact-teacher-field_training_hours_s1'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 21,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_s1',
    'label' => 'Spring Training Day 1 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 19,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_s2'
  $field_instances['e3_contact-teacher-field_training_hours_s2'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 22,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_s2',
    'label' => 'Spring Training Day 2 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 20,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_total'
  $field_instances['e3_contact-teacher-field_training_hours_total'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Automatically calculates total of all training hours',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 2,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_decimal',
        'weight' => 23,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_total',
    'label' => 'Total Training Hours Complete',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'prefix' => '',
      'read-only' => FALSE,
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'mathfield',
      'settings' => array(),
      'type' => 'mathfield_markup',
      'weight' => 21,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_w1'
  $field_instances['e3_contact-teacher-field_training_hours_w1'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 19,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_w1',
    'label' => 'Winter Training Day 1 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 17,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_training_hours_w2'
  $field_instances['e3_contact-teacher-field_training_hours_w2'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 20,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_training_hours_w2',
    'label' => 'Winter Training Day 2 Hours',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 18,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_work_email'
  $field_instances['e3_contact-teacher-field_work_email'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_work_email',
    'label' => 'Work email',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'e3_contact-teacher-field_work_phone'
  $field_instances['e3_contact-teacher-field_work_phone'] = array(
    'bundle' => 'teacher',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'e3_contact',
    'field_name' => 'field_work_phone',
    'label' => 'Work phone',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment-field_class_content'
  $field_instances['e3_note-class_assessment-field_class_content'] = array(
    'bundle' => 'class_assessment',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_class_content',
    'label' => 'Content',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'select_or_other',
      'settings' => array(
        'available_options' => 'lang|Lit/Lang Arts
socst|Social Studies
math|Math
art|Art
sci|Science',
        'available_options_php' => '',
        'markup_available_options_php' => '&lt;none&gt;',
        'other' => 'Other',
        'other_size' => 60,
        'other_title' => '',
        'other_unknown_defaults' => 'other',
        'sort_options' => 0,
      ),
      'type' => 'select_or_other_buttons',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment-field_class_format'
  $field_instances['e3_note-class_assessment-field_class_format'] = array(
    'bundle' => 'class_assessment',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_class_format',
    'label' => 'Format',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_adults_present'
  $field_instances['e3_note-class_assessment_it-field_adults_present'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_adults_present',
    'label' => 'Number of adults in classroom',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_children_present'
  $field_instances['e3_note-class_assessment_it-field_children_present'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_children_present',
    'label' => 'Number of children in classroom',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_class_activity'
  $field_instances['e3_note-class_assessment_it-field_class_activity'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_class_activity',
    'label' => 'Activity Setting',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'select_or_other',
      'settings' => array(
        'available_options' => 'napping|Napping
feeding|Feeding
play|Play
diapering|Diapering',
        'available_options_php' => '',
        'markup_available_options_php' => '&lt;none&gt;',
        'other' => 'Other',
        'other_size' => 60,
        'other_title' => '',
        'other_unknown_defaults' => 'other',
        'sort_options' => 0,
      ),
      'type' => 'select_or_other_buttons',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_class_english'
  $field_instances['e3_note-class_assessment_it-field_class_english'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_class_english',
    'label' => 'Primary Language English',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_class_physical'
  $field_instances['e3_note-class_assessment_it-field_class_physical'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_class_physical',
    'label' => 'Physical Setting',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'select_or_other',
      'settings' => array(
        'available_options' => 'classroom|Classroom
outside|Outside',
        'available_options_php' => '',
        'markup_available_options_php' => '&lt;none&gt;',
        'other' => 'Other',
        'other_size' => 60,
        'other_title' => '',
        'other_unknown_defaults' => 'other',
        'sort_options' => 0,
      ),
      'type' => 'select_or_other_buttons',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_ec_employer'
  $field_instances['e3_note-class_assessment_it-field_ec_employer'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_ec_employer',
    'label' => 'Program',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'taxonomy',
      'settings' => array(
        'autocomplete_path' => 'taxonomy/autocomplete',
        'size' => 60,
      ),
      'type' => 'taxonomy_autocomplete',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_ec_teacher'
  $field_instances['e3_note-class_assessment_it-field_ec_teacher'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_ec_teacher',
    'label' => 'Teacher',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_els_cycle_1'
  $field_instances['e3_note-class_assessment_it-field_els_cycle_1'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 29,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_els_cycle_1',
    'label' => 'Early Language Support Cycle 1',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 26,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_els_cycle_2'
  $field_instances['e3_note-class_assessment_it-field_els_cycle_2'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 30,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_els_cycle_2',
    'label' => 'Early Language Support Cycle 2',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 27,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_els_cycle_3'
  $field_instances['e3_note-class_assessment_it-field_els_cycle_3'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 31,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_els_cycle_3',
    'label' => 'Early Language Support Cycle 3',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 28,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_els_cycle_4'
  $field_instances['e3_note-class_assessment_it-field_els_cycle_4'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 32,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_els_cycle_4',
    'label' => 'Early Language Support Cycle 4',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 29,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_els_notes'
  $field_instances['e3_note-class_assessment_it-field_els_notes'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 11,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_els_notes',
    'label' => 'Early Language Support Notes',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 31,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_fe_cycle_1'
  $field_instances['e3_note-class_assessment_it-field_fe_cycle_1'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 25,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_fe_cycle_1',
    'label' => 'Facilitated Exploration Cycle 1',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 20,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_fe_cycle_2'
  $field_instances['e3_note-class_assessment_it-field_fe_cycle_2'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 26,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_fe_cycle_2',
    'label' => 'Facilitated Exploration Cycle 2',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 21,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_fe_cycle_3'
  $field_instances['e3_note-class_assessment_it-field_fe_cycle_3'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 27,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_fe_cycle_3',
    'label' => 'Facilitated Exploration Cycle 3',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 22,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_fe_cycle_4'
  $field_instances['e3_note-class_assessment_it-field_fe_cycle_4'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 28,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_fe_cycle_4',
    'label' => 'Facilitated Exploration Cycle 4',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 23,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_fe_notes'
  $field_instances['e3_note-class_assessment_it-field_fe_notes'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 10,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_fe_notes',
    'label' => 'Facilitated Exploration Notes',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 25,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_rc_cycle_1'
  $field_instances['e3_note-class_assessment_it-field_rc_cycle_1'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 17,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_rc_cycle_1',
    'label' => 'Relational Climate Cycle 1',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_rc_cycle_2'
  $field_instances['e3_note-class_assessment_it-field_rc_cycle_2'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 18,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_rc_cycle_2',
    'label' => 'Relational Climate Cycle 2',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_rc_cycle_3'
  $field_instances['e3_note-class_assessment_it-field_rc_cycle_3'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 19,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_rc_cycle_3',
    'label' => 'Relational Climate Cycle 3',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_rc_cycle_4'
  $field_instances['e3_note-class_assessment_it-field_rc_cycle_4'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 20,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_rc_cycle_4',
    'label' => 'Relational Climate Cycle 4',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_rc_notes'
  $field_instances['e3_note-class_assessment_it-field_rc_notes'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_rc_notes',
    'label' => 'Relational Climate Notes',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_time_of_observation'
  $field_instances['e3_note-class_assessment_it-field_time_of_observation'] = array(
    'bundle' => 'class_assessment_it',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'date',
        'settings' => array(
          'format_type' => 'long',
          'fromto' => 'both',
          'multiple_from' => '',
          'multiple_number' => '',
          'multiple_to' => '',
          'show_remaining_days' => FALSE,
          'show_repeat_rule' => 'show',
        ),
        'type' => 'date_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_time_of_observation',
    'label' => 'Time of Observation',
    'required' => 0,
    'settings' => array(
      'default_value' => 'now',
      'default_value2' => 'same',
      'default_value_code' => '',
      'default_value_code2' => '',
      'entity_translation_sync' => FALSE,
      'restrictions' => array(
        'allowed_values' => array(
          'type' => 'disabled',
        ),
        'max' => array(
          'date' => array(
            'day' => 9,
            'month' => 11,
            'year' => 2015,
          ),
          'host_entity_date' => array(
            'end_date' => 0,
            'field' => '',
          ),
          'type' => 'disabled',
        ),
        'min' => array(
          'date' => array(
            'day' => 9,
            'month' => 11,
            'year' => 2015,
          ),
          'host_entity_date' => array(
            'end_date' => 0,
            'field' => '',
          ),
          'type' => 'disabled',
        ),
      ),
      'restrictions2' => array(
        'allowed_values' => array(
          'type' => 'disabled',
        ),
        'max' => array(
          'date' => array(
            'day' => 9,
            'month' => 11,
            'year' => 2015,
          ),
          'host_entity_date' => array(
            'end_date' => 0,
            'field' => '',
          ),
          'type' => 'disabled',
        ),
        'min' => array(
          'date' => array(
            'day' => 9,
            'month' => 11,
            'year' => 2015,
          ),
          'host_entity_date' => array(
            'end_date' => 0,
            'field' => '',
          ),
          'type' => 'disabled',
        ),
      ),
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'date',
      'settings' => array(
        'increment' => 5,
        'input_format' => 'm/d/Y - H:i:s',
        'input_format_custom' => '',
        'label_position' => 'above',
        'no_fieldset' => 1,
        'repeat_collapsed' => 0,
        'text_parts' => array(),
        'year_range' => '-1:+1',
      ),
      'type' => 'date_popup',
      'weight' => 0,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_ts_cycle_1'
  $field_instances['e3_note-class_assessment_it-field_ts_cycle_1'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 21,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_ts_cycle_1',
    'label' => 'Teacher Sensitivity Cycle 1',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 14,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_ts_cycle_2'
  $field_instances['e3_note-class_assessment_it-field_ts_cycle_2'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 22,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_ts_cycle_2',
    'label' => 'Teacher Sensitivity Cycle 2',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_ts_cycle_3'
  $field_instances['e3_note-class_assessment_it-field_ts_cycle_3'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 23,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_ts_cycle_3',
    'label' => 'Teacher Sensitivity Cycle 3',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 16,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_ts_cycle_4'
  $field_instances['e3_note-class_assessment_it-field_ts_cycle_4'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 24,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_ts_cycle_4',
    'label' => 'Teacher Sensitivity Cycle 4',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 17,
    ),
  );

  // Exported field_instance: 'e3_note-class_assessment_it-field_ts_notes'
  $field_instances['e3_note-class_assessment_it-field_ts_notes'] = array(
    'bundle' => 'class_assessment_it',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 9,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_ts_notes',
    'label' => 'Teacher Sensitivity Notes',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 19,
    ),
  );

  // Exported field_instance: 'e3_note-observation_log-field_observation_duration'
  $field_instances['e3_note-observation_log-field_observation_duration'] = array(
    'bundle' => 'observation_log',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'hms_field',
        'settings' => array(
          'format' => 'h:mm',
          'leading_zero' => TRUE,
        ),
        'type' => 'hms_default_formatter',
        'weight' => 84,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_observation_duration',
    'label' => 'Observation Duration',
    'required' => 0,
    'settings' => array(
      'default_description' => 1,
      'entity_translation_sync' => FALSE,
      'format' => 's',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'hms_field',
      'settings' => array(),
      'type' => 'hms_default_widget',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'e3_note-session_log-field_observation_duration'
  $field_instances['e3_note-session_log-field_observation_duration'] = array(
    'bundle' => 'session_log',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'hms_field',
        'settings' => array(
          'format' => 'h:mm',
          'leading_zero' => TRUE,
        ),
        'type' => 'hms_default_formatter',
        'weight' => 21,
      ),
    ),
    'entity_type' => 'e3_note',
    'field_name' => 'field_observation_duration',
    'label' => 'Session Duration',
    'required' => 0,
    'settings' => array(
      'default_description' => 1,
      'entity_translation_sync' => FALSE,
      'format' => 's',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'hms_field',
      'settings' => array(),
      'type' => 'hms_default_widget',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Activity Setting');
  t('Automatically calculates total of all training hours');
  t('Cohort');
  t('Content');
  t('Early Language Support Cycle 1');
  t('Early Language Support Cycle 2');
  t('Early Language Support Cycle 3');
  t('Early Language Support Cycle 4');
  t('Early Language Support Notes');
  t('Email');
  t('Employing Early Childhood Center');
  t('Facilitated Exploration Cycle 1');
  t('Facilitated Exploration Cycle 2');
  t('Facilitated Exploration Cycle 3');
  t('Facilitated Exploration Cycle 4');
  t('Facilitated Exploration Notes');
  t('Fall Training Day 1 Hours');
  t('Fall Training Day 2 Hours');
  t('Fall Training Day 3 Hours');
  t('Format');
  t('Home address');
  t('Mid-Fall Training Day 1 Hours');
  t('Mid-Fall Training Day 2 Hours');
  t('Number of adults in classroom');
  t('Number of children in classroom');
  t('Observation Duration');
  t('Physical Setting');
  t('Position / role');
  t('Primary Language English');
  t('Program');
  t('Relational Climate Cycle 1');
  t('Relational Climate Cycle 2');
  t('Relational Climate Cycle 3');
  t('Relational Climate Cycle 4');
  t('Relational Climate Notes');
  t('Session Duration');
  t('Spring Training Day 1 Hours');
  t('Spring Training Day 2 Hours');
  t('Status');
  t('Teacher');
  t('Teacher Sensitivity Cycle 1');
  t('Teacher Sensitivity Cycle 2');
  t('Teacher Sensitivity Cycle 3');
  t('Teacher Sensitivity Cycle 4');
  t('Teacher Sensitivity Notes');
  t('Time of Observation');
  t('Total Training Hours Complete');
  t('Training Attendance');
  t('Winter Training Day 1 Hours');
  t('Winter Training Day 2 Hours');
  t('Work email');
  t('Work phone');

  return $field_instances;
}
