<?php

/**
 * Implements hook_entity_info().
 */
function esdportal_contact_entity_info() {
  $return = array(
    'esdportal_contact' => array(
      'label' => t('Contact'),
      'entity class' => 'EsdportalContact',
      'controller class' => 'EsdportalContactController',
      'base table' => 'esdportal_contact',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'cid',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'type',
      ),
      'bundles' => array(),
      'load hook' => 'esdportal_contact_load',
      'view modes' => array(
        'full' => array(
          'label' => t('Default'),
          'custom settings' => FALSE,
        ),
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'esdportal_contact',
      'access callback' => 'esdportal_contact_access',
    ),
  );
  $return['esdportal_contact_type'] = array(
    'label' => t('Contact Type'),
    'entity class' => 'EsdportalContactType',
    'controller class' => 'EsdportalContactTypeController',
    'base table' => 'esdportal_contact_type',
    'fieldable' => FALSE,
    'bundle of' => 'esdportal_contact',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'module' => 'esdportal_contact',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/contact-types',
      'file' => 'esdportal_contact.admin.inc',
      'controller class' => 'EsdportalContactTypeUIController',
    ),
    'access callback' => 'esdportal_contact_type_access',
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function esdportal_contact_entity_info_alter(&$entity_info) {
  foreach (esdportal_contact_types() as $type => $info) {
    $entity_info['esdportal_contact']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/contact-types/manage/%esdportal_contact_type',
        'real path' => 'admin/structure/contact-types/manage/' . $type,
        'bundle argument' => 4,
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function esdportal_contact_menu() {
  $items = array();

  $items['contact/add'] = array(
    'title' => 'Add contact',
    'page callback' => 'esdportal_contact_admin_add_page',
    'access arguments' => array('administer esdportal_contact entities'),
    'file' => 'esdportal_contact.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'tab_parent' => 'contact',
    'tab_root' => 'contact',
  );

  $contact_uri = 'contact/%esdportal_contact';
  $contact_uri_argument_position = 1;

  $items[$contact_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('esdportal_contact', $contact_uri_argument_position),
    'page callback' => 'esdportal_contact_view',
    'page arguments' => array($contact_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'esdportal_contact', $contact_uri_argument_position),
    'file' => 'esdportal_contact.pages.inc',
  );

  $items[$contact_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items[$contact_uri . '/delete'] = array(
    'title' => 'Delete contact',
    'title callback' => 'esdportal_contact_label',
    'title arguments' => array($contact_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('esdportal_contact_delete_form', $contact_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'esdportal_contact', $contact_uri_argument_position),
    'file' => 'esdportal_contact.admin.inc',
  );

  $items[$contact_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('esdportal_contact_form', $contact_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'esdportal_contact', $contact_uri_argument_position),
    'file' => 'esdportal_contact.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  foreach (esdportal_contact_types() as $type => $info) {
    $items['contact/add/' . $type] = array(
      'title' => 'Add contact/',
      'page callback' => 'esdportal_contact_add',
      'page arguments' => array(2),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'esdportal_contact', $type),
      'file' => 'esdportal_contact.admin.inc',
    );
  }

  $items['admin/structure/contact-types/%esdportal_contact_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('esdportal_contact_type_form_delete_confirm', 4),
    'access arguments' => array('administer esdportal_contact types'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'esdportal_contact.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function esdportal_contact_permission() {
  $permissions = array(
    'administer esdportal_contact types' => array(
      'title' => t('Administer contact types'),
      'description' => t('Allows users to configure contact types and their fields.'),
      'restrict access' => TRUE,
    ),
    'create esdportal_contact entities' => array(
      'title' => t('Create contacts'),
      'description' => t('Allows users to create contacts.'),
      'restrict access' => TRUE,
    ),
    'view esdportal_contact entities' => array(
      'title' => t('View contacts'),
      'description' => t('Allows users to view contacts.'),
      'restrict access' => TRUE,
    ),
    'edit any esdportal_contact entities' => array(
      'title' => t('Edit any contacts'),
      'description' => t('Allows users to edit any contacts.'),
      'restrict access' => TRUE,
    ),
    'edit own esdportal_contact entities' => array(
      'title' => t('Edit own contacts'),
      'description' => t('Allows users to edit own contacts.'),
      'restrict access' => TRUE,
    ),
  );

  return $permissions;
}


/**
 * Implements hook_entity_property_info_alter().
 */
function esdportal_contact_entity_property_info_alter(&$info) {
  $properties = &$info['esdportal_contact']['properties'];
  $properties['created'] = array(
    'label' => t("Date created"),
    'type' => 'date',
    'description' => t("The date the node was posted."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer nodes',
    'schema field' => 'created',
  );
  $properties['changed'] = array(
    'label' => t("Date changed"),
    'type' => 'date',
    'schema field' => 'changed',
    'description' => t("The date the node was most recently updated."),
  );
  $properties['uid'] = array(
    'label' => t("Author"),
    'type' => 'user',
    'description' => t("The author of the contact."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer esdportal_contact entities',
    'required' => TRUE,
    'schema field' => 'uid',
  );
}


/*******************************************************************************
 ********************************* Task API's **********************************
 ******************************************************************************/

/**
 * Access callback for task.
 */
function esdportal_contact_access($op, $contact, $account = NULL, $entity_type = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('administer esdportal_contact entities', $account)
          || user_access('create esdportal_contact entities', $account);
    case 'view':
      return user_access('administer esdportal_contact entities', $account)
          || user_access('view esdportal_contact entities', $account);
    case 'edit':
      return user_access('administer esdportal_contact entities')
          || user_access('edit any esdportal_contact entities')
          || (user_access('edit own esdportal_contact entities') && ($contact->uid == $account->uid));
  }
}

/**
 * Load a task.
 */
function esdportal_contact_load($cid, $reset = FALSE) {
  $contacts = esdportal_contact_load_multiple(array($cid), array(), $reset);
  return reset($contacts);
}

/**
 * Load multiple contacts based on certain conditions.
 */
function esdportal_contact_load_multiple($cids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('esdportal_contact', $cids, $conditions, $reset);
}

/**
 * Save task.
 */
function esdportal_contact_save($contact) {
  entity_save('esdportal_contact', $contact);
}

/**
 * Delete single task.
 */
function esdportal_contact_delete($contact) {
  entity_delete('esdportal_contact', entity_id('esdportal_contact' ,$contact));
}

/**
 * Delete multiple contacts.
 */
function esdportal_contact_delete_multiple($contact_ids) {
  entity_delete_multiple('esdportal_contact', $contact_ids);
}


/*******************************************************************************
 ****************************** Task Type API's ********************************
 ******************************************************************************/

/**
 * Access callback for task Type.
 */
function esdportal_contact_type_access($op, $entity = NULL) {
  return user_access('administer esdportal_contact types');
}

/**
 * Load task Type.
 */
function esdportal_contact_type_load($contact_type) {
  return esdportal_contact_types($contact_type);
}

/**
 * List of task Types.
 */
function esdportal_contact_types($type_name = NULL) {
  $types = entity_load_multiple_by_name('esdportal_contact_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}

/**
 * Save task type entity.
 */
function esdportal_contact_type_save($contact_type) {
  entity_save('esdportal_contact_type', $contact_type);
}

/**
 * Delete single case type.
 */
function esdportal_contact_type_delete($contact_type) {
  entity_delete('esdportal_contact_type', entity_id('esdportal_contact_type' ,$contact_type));
}

/**
 * Delete multiple case types.
 */
function esdportal_contact_type_delete_multiple($contact_type_ids) {
  entity_delete_multiple('esdportal_contact_type', $contact_type_ids);
}

/**
  * Implements hook_views_api().
  */
function esdportal_contact_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'esdportal_contact'),
  );
}

